@hostname = localhost
@port = 4000
@host = {{hostname}}:{{port}}
@contentType = application/json

### Hello World
GET http://{{host}}/api/v1/hello HTTP/1.1


### health check (not versioned)
GET http://{{host}}/health HTTP/1.1
